# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# Retain the NuGet package cache between builds
cache:
  - src\packages -> **\packages.config

# version format
version: 0.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# http://blog.appveyor.com/2014/06/04/shallow-clone-for-git-repositories/
#shallow_clone: true

# scripts that run after cloning repository
install:
  - choco install gitversion.portable -y
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

assembly_info:
  patch: false

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  #publish_nuget: true             # package projects with .nuspec files and push to artifacts
  #publish_nuget_symbols: true    # generate and publish NuGet symbol packages

  # MSBuild verbosity level
  verbosity: minimal

before_build:
  - nuget restore src\cloudflare.net.sln
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

after_build:
  - nuget pack "%APPVEYOR_BUILD_FOLDER%\src\CloudFlare.NET\CloudFlare.NET.csproj" -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%" -Symbols 
  - appveyor PushArtifact "CloudFlare.NET.%GitVersion_NuGetVersion%.nupkg"
  - appveyor PushArtifact "CloudFlare.NET.%GitVersion_NuGetVersion%.symbols.nupkg"

#---------------------------------#
#       tests configuration       #
#---------------------------------#

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:

  # Slack
  - provider: Slack
    auth_token:
      secure: AkSNuuHmfzAFp2+Oq00NRQFOfrXl4ue08SHx0FC2WTeXSiZv8uVKI3ZBWns7HTcV
    channel: cloudflare_net
